name: Build and Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  release:
    runs-on: windows-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies (monorepo)
        run: npm ci --workspaces

      - name: Build and Publish Electron App
        run: npm run dist
        working-directory: AppTools
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
