name: Build and Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  release:
    runs-on: windows-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Fix electron version in package.json
        run: |
          $packageJson = Get-Content -Path "./AppTools/package.json" -Raw | ConvertFrom-Json
          $packageJson.devDependencies.electron = "29.0.0"
          $packageJson | ConvertTo-Json -Depth 10 | Set-Content -Path "./AppTools/package.json"

      - name: Install fs-extra in scripts folder
        run: npm install fs-extra --no-save
        working-directory: ./scripts

      - name: Install root dependencies
        run: npm install

      - name: Install AppServe dependencies
        run: npm install
        working-directory: ./AppServe

      - name: Install AppTools dependencies
        run: |
          npm install
          npm install -D electron@29.0.0 electron-builder@latest
        working-directory: ./AppTools

      - name: Run prepare-production script
        run: node ./scripts/prepare-production.js

      - name: Build Electron app with fixed version
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          cd AppTools
          npx vite build
          npx electron-builder --publish always

      - name: List release files
        run: |
          echo "Listing release directory content:"
          Get-ChildItem -Path ./release -Recurse | Select-Object FullName
