name: Build Diagnosis

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  diagnose:
    runs-on: windows-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Examine package.json
        run: |
          echo "Current AppTools package.json:"
          type ./AppTools/package.json

      - name: Clean install in AppTools
        run: |
          cd AppTools
          npm ci || npm install

      - name: Check installed Electron
        run: |
          cd AppTools
          npm list electron
          npm list electron-builder

      - name: Install explicit Electron version
        run: |
          cd AppTools
          npm uninstall electron electron-builder
          npm install --save-exact electron@29.0.0 electron-builder@24.6.4
          npm list electron
          npm list electron-builder

      - name: Create test electron-builder config
        run: |
          cd AppTools
          $content = @"
          {
            "appId": "com.test.app",
            "productName": "TestApp",
            "directories": {
              "output": "../test-output"
            },
            "win": {
              "target": "dir"
            }
          }
          "@
          $content | Out-File -FilePath electron-builder-test.json -Encoding utf8

      - name: Test electron-builder with explicit config
        run: |
          cd AppTools
          npx vite build
          npx electron-builder --config electron-builder-test.json
        env:
          ELECTRON_BUILDER_ALLOW_UNRESOLVED_DEPENDENCIES: true

      - name: Build with edited package.json
        run: |
          cd AppTools
          $packageJson = Get-Content -Path "package.json" -Raw | ConvertFrom-Json
          # Simplify build config
          $packageJson.build.directories.output = "../test-output-2"
          $packageJson.build.publish = $null
          $packageJson.build.win = @{ target = "dir" }
          $packageJson | ConvertTo-Json -Depth 10 | Set-Content -Path "package.json"

          # Show the modified package.json
          type package.json

          # Try to build
          npx vite build
          npx electron-builder --dir
        env:
          ELECTRON_BUILDER_ALLOW_UNRESOLVED_DEPENDENCIES: true
